name: "depcheck action"
description: "Analyze project dependencies using depcheck"
inputs:
  workdir:
    description: "Working directory to use"
    required: false
    default: "."
  config:
    description: "Config file to use"
    required: false
    default: ""
runs:
  using: "node12"
  main: "index.js"
